apiVersion: v1
clusters:
- cluster:
    server: http://localhost:6443 
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: my-user
  user:
    token: ""
