name: CD Pipeline

on:
  push:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG" > ~/../terraform/kubeconfig

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: your-docker-username/your-image-name:latest
         
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ../terraform/manifests/deployment.yaml
          kubectl apply -f ../terraform/manifests/service.yaml
        env:
          KUBECONFIG: ~/../terraform//config

      - name: Confirm Deployment
        run: |
          kubectl rollout status deployment/your-deployment-name
        env:
          KUBECONFIG: ~/../terraform/config
