name: Docker Image CI

permissions: read-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Lint the Docker image
      uses: hadolint/hadolint-action@v3.1.0

  lint-code:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install pylint
      run: pip install pylint

    - name: Run pylint
      run: pylint **/*.py

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4  

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install pytest
      run: pip install pytest

    - name: Run pytest
      run: pytest integration_test.py
  
  