name: Terrascan Kubernetes Manifest Scan

on:
  push:
    branches:
      - main  # Run scan on pushes to the main branch
  pull_request:
    branches:
      - main  # Run scan on PRs to the main branch

jobs:
  terrascan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terrascan
        run: |
          curl -L https://github.com/accurics/terrascan/releases/latest/download/terrascan-linux-amd64 -o terrascan
          chmod +x terrascan
          sudo mv terrascan /usr/local/bin/terrascan

      - name: Run Terrascan
        run: |
          terrascan scan -t k8s -p ./manifests
