name: CI

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get the latest Terrascan version
        id: get_version
        run: |
          echo "Fetching latest version of Terrascan..."
          response=$(curl -s -L https://api.github.com/repos/accurics/terrascan/releases/latest)
          echo "Response: $response"  # Debug log
          VERSION=$(echo "$response" | jq -r .tag_name)
          if [ -z "$VERSION" ]; then
            echo "Failed to fetch the latest version." >&2
            exit 1
          fi
          echo "Latest version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Set version using the environment file
      
      - name: Download Terrascan
        id: download
        run: |
            echo "Downloading Terrascan version $VERSION..."
            # Update this URL based on what you find on the releases page
            DOWNLOAD_URL="https://github.com/tenable/terrascan/releases/download/$VERSION/terrascan_${VERSION}_Windows_x86_64.tar.gz"
        
            echo "Download URL: $DOWNLOAD_URL"
            
            # Check the content type before downloading
            curl -I "$DOWNLOAD_URL"
        
            # Download the file with error handling
            curl -L -f -o terrascan.tar.gz "$DOWNLOAD_URL"
        
            # Check if the download was successful
            if [ $? -ne 0 ]; then
              echo "Download failed!" >&2
              exit 1
            fi
        
            # Use `tar -tzf` to list the contents of the tar.gz file without extracting
            echo "Downloaded file contents:"
            tar -tzf terrascan.tar.gz | head -n 10

      - name: Extract and Install Terrascan
        run: |
          echo "Extracting Terrascan..."
          # Check if the file exists
          if [[ -f terrascan.tar.gz ]]; then
            echo "File found. Extracting..."
            tar -xzf terrascan.tar.gz -C /usr/local/bin
            if [[ $? -eq 0 ]]; then
              echo "Extraction successful."
              chmod +x /usr/local/bin/terrascan
              rm terrascan.tar.gz  # Clean up the downloaded file
            else
              echo "Extraction failed." >&2
              exit 1
            fi
          else
            echo "File terrascan.tar.gz not found." >&2
            exit 1
          fi

      - name: Run Terrascan
        run: terrascan scan -t k8s -p ./manifests
