name: CI

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terrascan
        run: |
          # Get the latest version number
          VERSION=$(curl -s https://api.github.com/repos/accurics/terrascan/releases/latest | jq -r .tag_name)
          
          # Download and install Terrascan
          curl -L "https://github.com/accurics/terrascan/releases/download/${VERSION}/terrascan_$(uname -s)_$(uname -m).tar.gz" -o terrascan.tar.gz
          tar -xzf terrascan.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/terrascan
          rm terrascan.tar.gz  # Clean up the downloaded file

      - name: Run Terrascan
        run: terrascan scan -t k8s -p ./manifests
