name: CI

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get the latest Terrascan version
        id: get_version
        run: |
          echo "Fetching latest version of Terrascan..."
          VERSION=$(curl -s https://api.github.com/repos/accurics/terrascan/releases/latest | jq -r .tag_name)
          echo "Latest version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Download Terrascan
        id: download
        run: |
          echo "Downloading Terrascan version ${{ steps.get_version.outputs.version }}..."
          curl -L -o terrascan.tar.gz "https://github.com/accurics/terrascan/releases/download/${{ steps.get_version.outputs.version }}/terrascan_$(uname -s)_$(uname -m).tar.gz"
          
          # Check if the download was successful
          if [ $? -ne 0 ]; then
            echo "Download failed!"
            exit 1
          fi

          # Display the HTTP response code
          echo "HTTP Response Code: $(curl -s -o /dev/null -w '%{http_code}' "https://github.com/accurics/terrascan/releases/download/${{ steps.get_version.outputs.version }}/terrascan_$(uname -s)_$(uname -m).tar.gz")"

          # Display the first few lines of the downloaded file
          echo "Downloaded file contents:"
          head -n 10 terrascan.tar.gz

      - name: Extract and Install Terrascan
        run: |
          echo "Extracting Terrascan..."
          # Check the file type before extraction
          file terrascan.tar.gz
          tar -xzf terrascan.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/terrascan
          rm terrascan.tar.gz  # Clean up the downloaded file

      - name: Run Terrascan
        run: terrascan scan -t k8s -p ./manifests


