name: CI

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terrascan
        run: |
          curl -L https://github.com/accurics/terrascan/releases/latest/download/terrascan_$(uname -s)_$(uname -m).tar.gz | tar xz -C /usr/local/bin
          chmod +x /usr/local/bin/terrascan

      - name: Run Terrascan
        run: terrascan scan -t k8s -p ./manifests
