name: CI

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main  # Change this to your main branch

jobs:
  terrascan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'  # Use the latest version as needed

      - name: Install Terrascan
        run: |
          go install github.com/accurics/terrascan/cmd/terrascan@latest
          echo "::add-path::$(go env GOPATH)/bin"  # Ensure that the installed binary is in PATH

      - name: Run Terrascan
        run: terrascan scan -t k8s -p ./manifests

