name: CI

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get the latest Terrascan version
        id: get_version
        run: |
          response=$(curl -s -L https://api.github.com/repos/tenable/terrascan/releases/latest)
          VERSION=$(echo "$response" | jq -r .tag_name)
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Set version using the environment file
      
      - name: Download Terrascan
        id: download
        run: |
          DOWNLOAD_URL="https://github.com/tenable/terrascan/releases/download/$VERSION/terrascan_$VERSION_Linux_i386.tar.gz"
          curl -L -f -o terrascan.tar.gz "$DOWNLOAD_URL"

      - name: Extract and Install Terrascan
        run: |
          tar -xzf terrascan.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/terrascan
          rm terrascan.tar.gz  # Clean up

      - name: Run Terrascan for Terraform
        run: terrascan scan -t tf -p ./terraform

      - name: Run Terrascan for Kubernetes
        run: terrascan scan -t k8s -p ./terraform